wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1654221776
    t:
      1:
      - 1
      - 51
      - 54
      - 55
      3:
      - 4
      - 13
      - 16
      4: 3.9.12
      5: 0.12.17
      8:
      - 5
architecture:
  desc: null
  value: dynamicKAE
dataset:
  desc: null
  value: Sub-sampled cyclone dataset
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.05
